# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lmaria <lmaria@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/01/31 15:20:43 by lmaria            #+#    #+#              #
#    Updated: 2025/03/07 13:26:47 by lmaria           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

.PHONY: all clean fclean re makelibft makemlx


NAME = so_long
LIBFT = $(LIBFT_DIR)/libft.a
MLX = $(MLX_DIR)/libmlx.a

#Compilation flags
CC = cc
CFLAGS = -Wall -Wextra -Werror
MLX_FLAGS = -L$(MLX_DIR) -lmlx -lXext -lX11
LIBFT_FLAGS = -L$(LIBFT_DIR) -lft
LIBFT_INC = -I$(LIBFT_DIR)

# Directories
SRC_DIR = src
OBJ_DIR = obj
INC_DIR = includes
MLX_DIR = minilibx-linux
LIBFT_DIR = libft

# Source files
SRC_FILES =		main.c					map_parser.c	\
				map_checker.c 			display.c 		\
				window.c 				textures.c		\
				map_utils.c 			move_player.c 	\
				map_accessibility.c 	errors.c		\
				memory.c 				so_long.c
SRCS = $(addprefix $(SRC_DIR)/, $(SRC_FILES))
OBJS = $(addprefix $(OBJ_DIR)/, $(SRC_FILES:.c=.o))

# Rules
all: makelibft makemlx $(NAME)

$(NAME): $(OBJS) $(MLX) $(LIBFT)
	@echo "Compiling the executable $(NAME)..."
	$(CC) $(CFLAGS) $(OBJS) $(MLX_FLAGS) $(LIBFT_FLAGS) -o $(NAME)
	@echo "Executable $(NAME) created."


$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c $(INC_DIR)/*.h  Makefile | $(OBJ_DIR)
	$(CC) $(CFLAGS) -I$(INC_DIR) $(LIBFT_INC) -c $< -o $@

$(MLX_DIR)/libmlx.a : makemlx


$(LIBFT_DIR)/libft.a: makelibft 

$(OBJ_DIR):
	mkdir -p $(OBJ_DIR)
	
makemlx:
	@echo "Compiling the $(MLX_DIR) library..."
	$(MAKE) --no-print-directory -C $(MLX_DIR)

makelibft:
	@echo "Compiling the $(LIBFT_DIR) library..."
	$(MAKE) --no-print-directory -C $(LIBFT_DIR)

clean:
	@echo "Delete object files generated by $(LIBFT_DIR), $(MLX_DIR) and $(NAME)..."
	rm -rf $(OBJ_DIR)
	make clean --no-print-directory -C $(MLX_DIR)
	make clean --no-print-directory -C $(LIBFT_DIR)
	@echo "Object files deleted."


fclean: clean
	@echo "Delete executable  $(LIBFT) and $(NAME)..."
	rm -f $(NAME)
	make fclean --no-print-directory -C $(LIBFT_DIR)
	@echo "Executable $(LIBFT) and $(NAME) deleted."

re: fclean all

